### ISSUE TITLE
Andrew fails to build for Sublime Text 2

### ISSUE THREAD

**Issue by mcmillhj** [SergiJuanola/Andrew#4]
I just installed the plugin for Sublime Text 2 and after restarting ST2 I receive this error in the console: 

Reloading plugin /Users/mcmillhj/Library/Application Support/Sublime Text 2/Packages/Andrew/Andrew.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./Andrew.py", line 304
    print(line.decode("utf-8", "ignore"),end='')

I am assuming this is due to Python 3 support being added. Is there a workaround for Sublime Text 2 ?

**Comment by mcmillhj** [comment]
I was able to get this to compile by removing all of the `end=''` blocks from the file and by removing the period before thread_progress in `from .thread_progress import ThreadProgress`. It still fails when I attempt to create a new project however: 
`RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)`
